<a href="https://colab.research.google.com/github/RaHuL-J31/Python-For-DS-and-ML/blob/master/02_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Notes and Examples
### NumPy is a Linear Algebra Library for Python.
#### Numpy comes with vectors and matrices
#### vectors are 1D arrays and matrices are 2D

In [ ]:
import numpy as np

In [ ]:
#1D array
my_list = [1,2,3]
arr = np.array(my_list)
arr

array([1, 2, 3])

In [ ]:
#2D array
my_mat = [[1,2],[2,3],[3,4]]
np.array(my_mat)

array([[1, 2],
       [2, 3],
       [3, 4]])

###built in way to create array

In [ ]:
#same as range function
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#if only even needed
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
#if only 0's needed
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
#if 2D 0's needed in below 2 row 3 column
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#for ones
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
#linspace to create division it creates 10 division from 0 to 5
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [ ]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

##Identity Matrix

In [ ]:
#Identity matrices are always square matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#for creating random value between 0 to 1
np.random.rand(5)

array([0.63738127, 0.81480729, 0.9095164 , 0.72173366, 0.62425346])

In [ ]:
np.random.rand(4,4)

array([[0.84143537, 0.37473014, 0.90821034, 0.00343192],
       [0.21883468, 0.21777289, 0.45991605, 0.56104757],
       [0.89243258, 0.2707762 , 0.72548716, 0.02943827],
       [0.51515482, 0.19472411, 0.15714913, 0.15214545]])

In [ ]:
np.random.randn(5)

array([ 0.96694118,  0.47719049,  0.87709214, -0.19249671, -0.4099596 ])

In [ ]:
np.random.randn(3,3)

array([[ 0.87778576, -1.25624659,  0.8167882 ],
       [-1.79603582, -1.7635585 , -0.893205  ],
       [ 0.18765728, -0.75967234, -0.16579106]])

In [ ]:
#random integer below 100
np.random.randint(1,100)

20

In [ ]:
#10 random integer below 100
np.random.randint(1,100,10)

array([ 9,  4, 92, 17, 30,  8, 49, 17, 18, 66])

In [ ]:
#reshape 
arr = np.arange(25)
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
#Max and Min
ranarr = np.random.randint(0,100,10)
ranarr

array([79, 65, 88,  1, 82, 68, 14, 45, 95, 49])

In [ ]:
ranarr.max()

95

In [ ]:
ranarr.min()

1

In [ ]:
#gives location of max val
ranarr.argmax()

8

In [ ]:
ranarr.argmin()

3

In [ ]:
#shows 
ranarr.shape

(10,)

In [ ]:
#shows datatype of array
arr.dtype

dtype('int64')

In [ ]:
#insted of np.random.randint(10)
from numpy.random import randint
randint(10)

3

##Index and Selection

In [ ]:
arr = np.arange(0,11)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[5]

5

In [ ]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [ ]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
copy_of_arrr = arr.copy()
copy_of_arrr[:5] = 7
copy_of_arrr

array([ 7,  7,  7,  7,  7,  5,  6,  7,  8,  9, 10])

In [ ]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d[0][2]

3

In [ ]:
#or you can use
arr_2d[0,2]

3

In [ ]:
#slicing of 2d array
#everything till 2nd row
arr_2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#only first 2 colums
arr_2d[:2,:2]

array([[1, 2],
       [4, 5]])

In [ ]:
arr = np.arange(0,10)
print(arr[arr>5])


[6 7 8 9]


## NumPy Operations

In [ ]:
arr = np.arange(10)

In [ ]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr*5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
np.max(arr)

9

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
angle = [0,30,45,60,90]
a = np.array(angle)
np.sin(a)

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666])

In [ ]:
np.cos(a)

array([ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362])